// try and catch statement is used to handle the exceptions.
// like last topic-exception handling of PL/SQL in college

{
    // try and catch statement is used to handle the exxceptions.
    // try{
        // body of try
    // }
    // catch{
        // body of catch
    // }
}


// Display undeclare variables


    // const numerator = 100 , denomitor = 20;

    // try{
        // console.log(numerator / denomitor);
 
    // forgot to define variable a 

    // let a;
    // try{
    //     // let a = 5;
    // console.log(a);
    // console.log('Hello');
    // }
    // catch(error){
    //     console.log('An error Caught');
    //     console.log('Error message is :' + error);
    // }
    // finally{
    //     console.log('Finally will execute every time');
    // }




// Javascript throw statement

{
    // throw expression;
}

{
    // const number = 5 ;
    // throw number/0; //generate en exception when devided by 0

    // throw with try...catch

    // {
    //     try{
    //         // body of try
    //         throw exception;
    //     }
    //     catch(error){
    //         // body of catch

    //     }
    // }

}

// try...catch...throw

{
    // const number = 20;
    // try{
    //     if(number > 50)
    //     {
    //         console.log('success');
    //     }
    //     else
    //     {
    //         throw new Error('Number is low'); 
    //     }
    //     // if throw executes, the below code does not execute
    //     console.log('hello');
    // }
    // catch(error)
    // {
    //     console.log('Catch An error');
    //     console.log('Error message'+ error);
    // }
}

